spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: table-service
          uri: http://localhost:8086/tables/
          predicates:
          - Path=/tables/**
        - id: reservation-service
          uri: http://localhost:8086/reservations/
          predicates:
          - Path=/reservations/**

server:
    port: 8989