version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    networks:
      - restaurant
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
    networks:
      - restaurant
  kafka-service:
    container_name: kafka-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-kafka-service
    ports:
      - 9000:9000
    networks:
      - restaurant
    environment:
      SERVER_IP: ${SERVER_IP}
networks:
  restaurant:
    name: restaurant
    driver: bridge
