spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
        - id: table-service
          uri: lb://TABLE-SERVICE
          predicates:
            - Path=/tables/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu/**
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

server:
  port: 8989