FROM openjdk
ADD target/RestaurantReservationService-0.0.1-SNAPSHOT.jar RestaurantReservationService-0.0.1-SNAPSHOT.jar
EXPOSE 8089
ENTRYPOINT ["java" , "-jar","RestaurantReservationService-0.0.1-SNAPSHOT.jar"]