eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.203.146.96:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_IP}
