eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.202.53.123:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.214.81.177
