version: "3.3"
services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-user-service
    ports:
      - 8085:8085
    networks:
      - restaurant
    environment:
      SERVER_IP: ${SERVER_IP}
networks:
  restaurant:
    name: restaurant
    driver: bridge